import Link from "next/link"; import { ArrowDownRight } from "lucide-react"; import { activeServices, company } from "@/data/config"; import { ServiceCard } from "@/components/service-card"; import { whatsappUrl } from "@/lib/whatsapp";
export default function Home(){return <>
<section className="container-page grid min-h-[calc(100vh-5rem)] items-center gap-8 py-10 lg:grid-cols-[1.1fr_.9fr]"><div><p className="eyebrow mb-6">Timeless · Rwanda</p><h1 className="display">Made for moments that matter.</h1><p className="mt-8 max-w-xl leading-7 text-black/65">{company.description}</p><div className="mt-9 flex flex-wrap gap-3"><Link className="btn btn-dark" href="/memories">Explore Memories</Link><Link className="btn" href="/tailoring">Explore Tailoring</Link></div></div><div className="media-placeholder min-h-[60vh]"/></section>
<section className="container-page py-28 text-center"><p className="eyebrow">Our philosophy</p><h2 className="heading mx-auto mt-5 max-w-3xl">Some moments deserve to last.</h2><p className="mx-auto mt-7 max-w-2xl leading-7 text-black/60">Timeless creates personalized pieces and experiences designed around life&apos;s meaningful occasions — from wedding memories created with the people you love to clothing made especially for you.</p></section>
<section className="container-page grid gap-4 pb-28 md:grid-cols-2">{[["Timeless Memories","Turn the people, messages and emotions of your celebration into something you can keep long after the day is over.","/memories"],["Timeless Tailoring","Made around you — your measurements, your occasion and your style.","/tailoring"]].map(([title,copy,href],i)=><Link href={href} key={href} className={`group flex min-h-[36rem] flex-col justify-end p-8 text-white ${i?'bg-[#47443f]':'bg-[#817367]'}`}><p className="font-serif text-5xl">{title}</p><p className="mt-4 max-w-md text-sm leading-6 text-white/75">{copy}</p><ArrowDownRight className="mt-7 transition group-hover:translate-x-1 group-hover:translate-y-1"/></Link>)}</section>
<section className="bg-sand py-28"><div className="container-page"><p className="eyebrow">Timeless Memories</p><h2 className="heading mt-5">Memories made together.</h2><div className="mt-14 grid gap-x-16 lg:grid-cols-2">{activeServices("memories").map(s=><ServiceCard service={s} key={s.slug}/>)}</div></div></section>
<section className="container-page py-28"><p className="eyebrow">The process</p><h2 className="heading mt-5">A considered journey.</h2><div className="mt-14 grid gap-8 md:grid-cols-4">{["Choose your experience","Tell us about your event","We personalize it","Make the memory"].map((x,i)=><div className="border-t border-black/30 pt-5" key={x}><span className="text-xs">0{i+1}</span><h3 className="mt-5 font-serif text-2xl">{x}</h3></div>)}</div></section>
<section className="bg-[#9b8c7c] py-28 text-center text-white"><h2 className="heading">Your moment. Your story.<br/>Made timeless.</h2><div className="mt-9 flex justify-center gap-3"><Link href="/book" className="btn border-white bg-white text-ink">Book with Timeless</Link><a href={whatsappUrl()} className="btn border-white">Talk on WhatsApp</a></div></section>
</>}
