"use client";
import { useMemo, useState } from "react"; import { useSearchParams } from "next/navigation"; import { activeServices } from "@/data/config"; import { whatsappUrl } from "@/lib/whatsapp";
type Division="memories"|"tailoring";
export function BookingForm(){const query=useSearchParams();const initial=(query.get("division")==="tailoring"?"tailoring":query.get("division")==="memories"?"memories":null) as Division|null;const [division,setDivision]=useState<Division|null>(initial);const [step,setStep]=useState(initial?1:0);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [reference,setReference]=useState("");const list=useMemo(()=>division?activeServices(division):[],[division]);
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const form=new FormData(e.currentTarget);const payload=Object.fromEntries(form.entries());try{const r=await fetch("/api/enquiries",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload,division})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Unable to send your request.");setReference(data.reference)}catch(err){setError(err instanceof Error?err.message:"Unable to send your request.")}finally{setBusy(false)}}
if(reference)return <div className="max-w-2xl"><p className="eyebrow">Request {reference}</p><h2 className="heading mt-5">Thank you.</h2><p className="mt-7 leading-7 text-black/65">Your request has been received. Timeless will contact you to confirm the details and availability.</p><a className="btn btn-dark mt-8" href={whatsappUrl(`Hello Timeless, I have submitted enquiry ${reference}.`)}>Continue on WhatsApp</a></div>;
if(step===0)return <div><p className="eyebrow">Start your request</p><h2 className="heading mt-5">What are you interested in?</h2><div className="mt-12 grid max-w-3xl gap-4 sm:grid-cols-2">{(["memories","tailoring"] as Division[]).map(d=><button onClick={()=>{setDivision(d);setStep(1)}} className="min-h-48 border border-black/20 p-8 text-left font-serif text-4xl capitalize transition hover:bg-ink hover:text-white" key={d}>Timeless {d}</button>)}</div></div>;
return <form className="max-w-3xl" onSubmit={submit}><button type="button" onClick={()=>setStep(0)} className="eyebrow">← Change division</button><h2 className="heading mt-6">Tell us about your {division==="memories"?"occasion":"request"}.</h2><input type="hidden" name="type" value={division||""}/><div className="mt-10 grid gap-x-8 gap-y-5 sm:grid-cols-2"><Field name="customer_name" label="Your name" required/><Field name="phone" label="Phone / WhatsApp" required type="tel"/><Field name="email" label="Email" type="email"/><label>Service<select className="field" name="service" defaultValue={query.get("service")||""} required><option value="" disabled>Choose a service</option>{list.map(s=><option value={s.slug} key={s.slug}>{s.name}</option>)}</select></label>{division==="memories"?<><Field name="event_type" label="Type of event"/><Field name="event_date" label="Event date" type="date"/><Field name="location" label="Event location / venue"/><Field name="guest_count" label="Expected guests" type="number"/><Field name="names" label="Couple / celebrant names"/><Field name="theme" label="Preferred theme / colours"/></>:<><Field name="occasion" label="Occasion"/><Field name="needed_date" label="Date needed" type="date"/><label>Measurements<select className="field" name="measurements"><option>I need to be measured</option><option>I already have my measurements</option></select></label><Field name="fitting_date" label="Preferred fitting date" type="date"/><Field name="location" label="Location"/></>}<Field name="budget" label="Budget range (optional)"/><label className="sm:col-span-2">Tell us more<textarea name="notes" rows={4} className="field"/></label><label>Preferred contact<select className="field" name="preferred_contact"><option>WhatsApp</option><option>Phone</option><option>Email</option></select></label></div>{error&&<p className="mt-6 text-sm text-red-800" role="alert">{error}</p>}<button disabled={busy} className="btn btn-dark mt-9 disabled:opacity-50">{busy?"Sending…":division==="memories"?"Request your Timeless experience":"Request tailoring"}</button></form>}
function Field({name,label,type="text",required=false}:{name:string;label:string;type?:string;required?:boolean}){return <label>{label}<input className="field" name={name} type={type} required={required}/></label>}
